[workspace]
members = [
    "summerset_server",
    "summerset_client",
    "summerset_bench",
]

[package]
name = "summerset"
description = "Distributed KV-store for SMR Protocol Research Purposes"
version = "0.1.0"
edition = "2021"
authors = ["Guanzhou Jose Hu <huguanzhou123@gmail.com>"]

[dependencies]
tonic = "0.8"
prost = "0.11"
tokio = { version = "1.22", features = ["macros", "rt-multi-thread"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.8"
