[workspace]
members = ["summerset_server", "summerset_client"]

[package]
name = "summerset"
description = "Distributed KV-store for SMR Protocol Research Purposes"
version = "0.1.0"
edition = "2021"
authors = ["Guanzhou Jose Hu <huguanzhou123@gmail.com>"]

[dependencies]
async-trait = "0.1"
fixedbitset = "0.4"
flashmap = "0.1"
bytes = "1.4"
futures = "0.3"
tokio = { version = "1.29", features = ["full"] }
rand = "0.8"
lazy_static = "1.4"
rmp-serde = "1.1"
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.7", features = ["parse"] }
log = "0.4"
