[package]
name = "summerset_client"
description = "Summerset client side library"
version = "0.1.0"
edition = "2021"
authors = ["Guanzhou Jose Hu <huguanzhou123@gmail.com>"]

[dependencies]
summerset = { path = "../" }
tonic = "0.8"
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"] }
log = "0.4"
