[package]
name = "summerset_server"
description = "Summerset server node executable"
version = "0.1.0"
edition = "2021"
authors = ["Guanzhou Jose Hu <huguanzhou123@gmail.com>"]

[dependencies]
summerset = { path = "../" }
tonic = "0.8"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.0", features = ["derive"] }
