name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get protobuf
      run: sudo apt install -y protobuf-compiler libprotobuf-dev
    - name: Run tests
      run: cargo test --workspace --verbose
